

surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/LocalAreaNetwork.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/Unbreak.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list,28800
surge_ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
surge_ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/Media/Bahamut.list
surge_ruleset=🛑 劫持拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
surge_ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
surge_ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
surge_ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
surge_ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
surge_ruleset=🎶 TikTok,[]GEOSITE,tiktok
surge_ruleset=🎮 Steam,[]GEOSITE,steam
surge_ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
surge_ruleset=💬 Ai平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
surge_ruleset=📺 AbemaTV,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/Media/AbemaTV.list
surge_ruleset=📲 电报吹水,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
surge_ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
surge_ruleset=🌏 BiliBili,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/HKMTMedia.list
surge_ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
surge_ruleset=🔰 节点选择,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/Global.list
surge_ruleset=🔰 节点选择,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/PROXY.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ipip.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/DIRECT.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/ConnersHua/Surge/Ruleset/China.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/whf1030/nameless13/master/rules/NobyDa/Surge/Download.list
;surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=🐟 规则外路由选择,[]FINAL



custom_proxy_group=🔰 节点选择`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`(?i:1X)
;custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`500
custom_proxy_group=📲 电报吹水`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`(新|狮城|SG|Singa|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=📹 YouTube`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`^((?!CN2|流量|时间).)*$
custom_proxy_group=🎥 NETFLIX`select`[]🔰 节点选择`[]🎥 奈非节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=🎶 TikTok`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=💬 Ai平台`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=🎮 Steam`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=📺 巴哈姆特`select`[]🔰 节点选择`[]🇨🇳 台湾节点`[]DIRECT`(台|新北|彰化|TW|Tai)
custom_proxy_group=📺 AbemaTV`select`[]🔰 节点选择`[]🇯🇵 日本节点`[]DIRECT`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|HONG|Hong|HGC)
custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 新加坡节点`select`(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇺🇸 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=🚀 其他节点`select`GCX`^((?!新|多伦多|哥伦布|纽约|弗里蒙特|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US).)*$
custom_proxy_group=🎥 奈非节点`select`(NF|解锁|Netflix|NETFLIX)`[]🚀 手动切换
custom_proxy_group=🚀 手动切换`select`^((?!流量|时间).)*$
custom_proxy_group=🌍 国外媒体`select`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 BiliBili`select`[]DIRECT`[]🚀 其他节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🔰 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=🛑 劫持拦截`select`[]REJECT`[]🔰 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🐟 规则外路由选择`select`[]🔰 节点选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🚀 其他节点`[]🚀 手动切换
